### ISSUE TITLE
Always use Forward Slash "/" for package paths

### ISSUE THREAD

**Issue by sampaioletti** [tkrajina/typescriptify-golang-structs#10]
From tscriptify/main.go:78

`packageParts := strings.Split(packagePath, string(os.PathSeparator))`

packages in go always use forward slash even on windows 

[https://stackoverflow.com/questions/45323772/invalid-import-path-go-windows](url)

should be 

`packageParts := strings.Split(packagePath, "/")`

**Comment by tkrajina** [comment]
Yes, you're right, silly mistake on my part.

Fixed now (https://github.com/tkrajina/typescriptify-golang-structs/commit/9191385c0f420349ff67b6e505c286108f21730f). Thanks!

**Comment by sampaioletti** [comment]
Yeah no worries, great library. Using it to get some type safety on our json-rpc calls. Working like a champ. Thanks!
