### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by gtsopour** [tkrajina/typescriptify-golang-structs#26]
Hello and thanks for this nice library.
Does this library support Enums somehow? Should the following be converted to a Typescript Enum https://www.typescriptlang.org/docs/handbook/enums.html? Please check bellow an example.

`type LeaveType string

const(
    AnnualLeave LeaveType = "AnnualLeave"
    Sick LeaveType = "Sick"
    BankHoliday LeaveType = "BankHoliday"
    Other LeaveType = "Other"
)`

**Comment by tkrajina** [comment]
https://github.com/tkrajina/typescriptify-golang-structs#enums
