### ISSUE TITLE
to interfaces

### ISSUE THREAD

**Issue by Narven** [tkrajina/typescriptify-golang-structs#41]
How are we supose to convert to interfaces instead of classes? Using the code in the readme

```
converter := typescriptify.New().
    Add(Person{}).
    Add(Dummy{})
err := converter.ConvertToFile("ts/models.ts")
if err != nil {
    panic(err.Error())
}
```

**Comment by tkrajina** [comment]
Committed a missing initialisation method now:
```
converter := typescriptify.New().
    WithInterface().
    ...
```

**Comment by Narven** [comment]
Its kind of hard to do this since ` WithInterface(true).` does not exist

**Comment by Narven** [comment]
@tkrajina why are you closing this?

There is NO WithInterface(true) in release 0.1.5

**Comment by tkrajina** [comment]
I'm closing it because it's there.

https://github.com/tkrajina/typescriptify-golang-structs/commit/1c95abb56327167a5330367f25231f7ac82dd7f0

I don't plan to create releases for every single commit. If you're using go modules you can easily point to a single commit.

**Comment by Narven** [comment]
Thanks
