### ISSUE TITLE
Prefix affects map keys

### ISSUE THREAD

**Issue by chanced** [tkrajina/typescriptify-golang-structs#44]
If you use a prefix, the prefix is prepended to map keys, including primitives. 

``` Go
type Example struct {
   Variable map[string]string `json:"variable"`
}

func main() {
    typescriptify.New().WithPrefix("Testing").Add(Example{}).ConvertToFile("./output.ts")
}
```
Will generate something like this:

```typescript
export class TestingExample {
    variable: {[key: Testingstring]: string};
}
```

It also affects all subtypes not specified. This could be desirable behavior but it may cause issues if the types are later or previously defined elsewhere.

**Comment by jamelt** [comment]
I'm observing this behavior as well.

**Comment by tkrajina** [comment]
Fixed now, thanks for reporting.
