### ISSUE TITLE
YAML tag spport

### ISSUE THREAD

**Issue by markszente** [tkrajina/typescriptify-golang-structs#46]
Hello, I've forked the repo and extended it so that YAML tags are also supported, alongside existing JSON support, of course. I'm not sure whether this is something the project could use, but I can make a PR if you guys want.

[Here's](https://github.com/markszente/typescriptify-golang-structs/commit/6019094e4bcdc19be55d1321f9f1b500e7fb225a) the commit.

**Comment by tkrajina** [comment]
Hm, I don't really see many use-cases for this. And adding it would mean adding a ton of new tests and things I'd need to mantain in the future :(

**Comment by markszente** [comment]
Yeah, fair enough. I didn't bother adding tests (although the test structs have been extended with yaml tags), because it's for internal/hobby use only, and it would have required some serious refactoring.
