### ISSUE TITLE
Error message to stderr

### ISSUE THREAD

**Issue by leaanthony** [tkrajina/typescriptify-golang-structs#55]
Hi - great project.

I noticed that there is a message that's being output to stderr and there's no way of disabling it because the logic test is always true:
https://github.com/tkrajina/typescriptify-golang-structs/blob/master/typescriptify/typescriptify.go#L131-L133

Happy to do a PR for this...

**Comment by tkrajina** [comment]
Ah, yes, you're right. I moved that warning in the `.Convert()` method and also changed the default of `CreateFromMethod` to `false`. That warning is showing for almost a year now.

**Comment by leaanthony** [comment]
Thanks. Let me know when you tag it and I'll switch from my fork. Thanks.

**Comment by tkrajina** [comment]
It's in `v0.1.7` now.
