### ISSUE TITLE
Translating Golang functions to TypeScript

### ISSUE THREAD

**Issue by jarble** [tkrajina/typescriptify-golang-structs#57]
Could this compiler be extended to translate Golang functions as well as Golang structs to TypeScript?
For example, this Go function could be easily translated to TypeScript:
```
func add(x f64, y f64) int {
	return x + y
}
```
This would be the equivalent function in TypeScript:
```
export function add(x:number,y:number):number{
    return x+y;
}
```
It is possible to translate a subset of Go to TypeScript in this way, and there are several other features of Go that could be easily translated:
* [`for`](https://gobyexample.com/for) loops would become `while` loops,
* [slices](https://go.dev/blog/slices-intro) would become arrays in TypeScript,
* [Generics in Go](https://go.dev/doc/tutorial/generics) would become [generics in TypeScript](https://www.typescriptlang.org/docs/handbook/2/generics.html)
* and many others: [anonymous functions](https://gobyexample.com/closures), [switch statements](https://gobyexample.com/switch), [type conversions](https://golangdocs.com/type-casting-in-golang), etc.

**Comment by PaluMacil** [comment]
I don't think you could easily extend this to a state where it would be broadly useful. Most code depends upon other libraries, including the standard library. If you include, those things, then a feature needs to know how to translate those or somehow replace them with Typescript equivalents with often varying syntax or quirks that don't match Go. This isn't to say you can't do this, but it's far larger in scope than this project and should not be here. Luckily, nearly what you want also already exists in the form of gopherjs. I recommend you take a look at that project for transpiling Go to Javascript.

**Comment by tkrajina** [comment]
@fairking What you're suggesting is a solution for a completely different problem than the one this library solves. Also, it's highly dependant on the http library/framework you use.

But, generally, transpiling code is something I don't plan to implement because it is way too complicated and I don't have the time to mantain that.
