### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by harnyk** [tkrajina/typescriptify-golang-structs#61]
I would like if the following struct:

```go
// Header Item
type HeaderItem struct {
	//Header name
	Name  string `json:"name"`
	//Header value
	Value string `json:"value"`
}
```

would convert to the following interface

```ts
/**
 * Header Item
 */
interface HeaderItem {
   /**
    * Header name
    */
   name: string;

   /**
    * Header value
    */
   value: string;
}
```

Is it possible? Other option would be to have a special tag:

```go
type HeaderItem struct {
	Name  string `json:"name" doc:"Header name"`
	Value string `json:"value" doc:"Header value"`
        _ struct{} `doc:"Header Item"`
}
```

**Comment by gzuidhof** [comment]
This library won't be able to support this as it's reflection based, you could consider using [tygo](https://github.com/gzuidhof/tygo) instead.

**Comment by tkrajina** [comment]
You make it sound like "reflection based" is something very bad @gzuidhof :) "Parser based" solves some problems but introduces others (for example - how about inner structs or structs in multiple packages).

Anyway... Adding a tag for specifying typescript comments is simple to implement @harnyk .

**Comment by tkrajina** [comment]
@harnyk Added a way to specify field comments, see https://github.com/tkrajina/typescriptify-golang-structs#field-comments
